on: pull_request
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - run: chmod +t -R /opt/hostedtoolcache
      - run: ruby bench_runner.rb
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add results
          git commit -m "Add benchmark result"
          git push origin HEAD:${{ github.head_ref }}
